### ISSUE TITLE
MRI cache backend causes unnecessary deadlock

### ISSUE THREAD

**Issue by jkl1337** [ruby-concurrency/thread_safe#22]
In the MriCacheBackend it states:
    # We can get away with a single global write lock (instead of a per-instance
    # one) because of the GVL/green threads.

While this is true it causes this to blow up:

```
c1 = ThreadSafe::Cache.new
c2 = ThreadSafe::Cache.new

c1.compute_if_absent('') { |k| c2.compute_if_absent(k) { 42 } }
```
While it is understandable that recursion is not supported for the same cache instance, the limitation across instances seems less defensible.

**Comment by thedarkone** [comment]
> While it is understandable that recursion is not supported for the same cache instance, the limitation across instances seems less defensible.

It **might seem** indefensible and seemingly easily fixable by making the lock per instance or making it re-entrant in general, unfortunately this only solves the issue on MRI (where no real concurrency exists).

All other implementations (JRuby, Rbx) might still deadlock. This is a big and often discussed limitation of CHMv8 design (brand new version of `ConcurrentHashMap` shipped in JDK8 that `TS::Cache` copies), see https://github.com/headius/thread_safe/issues/30 for `TS::Cache` or various concurrency-interest discussions about `computeIfAbsent`, for example: http://cs.oswego.edu/pipermail/concurrency-interest/2014-December/013360.html.

Note that googling might turn up pages (like [here](http://stackoverflow.com/questions/28840047/recursive-concurrenthashmap-computeifabsent-call-never-terminates-bug-or-fea/28845674#28845674) or [here](http://www.javacodegeeks.com/2015/03/avoid-recursion-in-concurrenthashmap-computeifabsent.html)) talking about patches "solving" the recursion problem, this however only pertains to `CHM` detecting some types of recursive calls on the same `CHM` instance and throwing an exception instead of deadlocking on the spot. No attempt has been made (or is general possible) to make multiple `CHM` "recursible" with each other.

Here's an example of deadlocking two instances of Java `ConcurrentHashMap`s (JDK8+) on JRuby:

```ruby
class Key
  attr_reader :hash, :key
  
  def initialize(key, hash)
    @key  = key
    @hash = hash
  end
  
  def eql?(other_key)
    other.kind_of?(self.class) && @key.eql?(other.key) && @hash == other.hash
  end
end

h1 = java.util.concurrent.ConcurrentHashMap.new
h2 = java.util.concurrent.ConcurrentHashMap.new

k1 = Key.new(:k1, 1)
k2 = Key.new(:k2, 2)

mutex              = Mutex.new
threads_in_compute = 0

Thread.new do
  h2.compute_if_absent(k2) do
    mutex.synchronize { threads_in_compute += 1 }
    sleep(0.01) while mutex.synchronize { threads_in_compute != 2 }

    h1.compute_if_absent(k1) {}
  end
end

h1.compute_if_absent(k1) do
  mutex.synchronize { threads_in_compute += 1 }
  sleep(0.01) while mutex.synchronize { threads_in_compute != 2 }
  
  h2.compute_if_absent(k2) {}
end
```

PS: however, for your example, if all the code paths interacting with `c1` and `c2` always call "compute" methods on `c1` first, then in fact they won't deadlock (on non MRI ruby VMs). Not sure if it is worth it to support the use case, I kinda like that this deadlocks on MRI right away (instead of unreproducibly deadlocking when the code is deployed and used concurrently by users).

**Comment by jkl1337** [comment]
> PS: however, for your example, if all the code paths interacting with c1 and c2 always call "compute"
> methods on c1 first, 

I think this usage scenario is far more common then you imply.
Imagine a connection or other resource pool implementation with a call graph to obtain a resource that terminates in stdlib calls and would never call into client code. Now TS::Cache cannot be used further up the call chain to implement a data cache without an auxiliary lock and additional code.

Multithreaded code has many ways to deadlock. If someone needs this feature they are just going to code it themselves with lock primitives which will not be any better. A threading library cannot prevent the user from shooting themselves in the foot. I still think per instance locks should be considered. I agree a reentrant lock is not a good solution.

**Comment by thedarkone** [comment]
Very good point about not being able to "wrap" a library in a `TS::Cache` if said library uses `TS::Cache` itself, thank you.

**Comment by jdantonio** [comment]
@thedarkone What's your final decision? Should we keep it as-is, or give each cache object it's own mutex?

**Comment by thedarkone** [comment]
Yeah, we'll have to roll with per instance `Mutex` for MRI backend.

**Comment by jdantonio** [comment]
Cool. I'll take care of it--both here and in concurrent-ruby.

**Comment by jdantonio** [comment]
@thedarkone If I understand the code correctly, the only different between `SynchronizedCacheBackend` and `MriCacheBackend` is the lock. The former uses a per-instance lock and the latter uses a single lock for all instances. So to implement a per-instance lock on MRI I simply need to get rid of `MriCacheBackend` and remove the "when 'ruby'" case from `cache.rb`. Is this correct?

**Comment by thedarkone** [comment]
No, `MriCacheBackend` synchronizes only some methods and relies on atomicity of MRI `Hash`'s methods for other things. For example `MriCacheBackend` has lock-free reads, while `SynchronizedCacheBackend` doesn't.

**Comment by thedarkone** [comment]
https://gist.github.com/thedarkone/d98c45d959241ad6071f

**Comment by jdantonio** [comment]
This update has been made as part of [concurrent-ruby PR #386 "Import `thread_safe` gem"](https://github.com/ruby-concurrency/concurrent-ruby/pull/386). It will go live in the 1.0.0.pre1 release.
